fendi_shop/fendi/urls.py
from django.urls import path
from .views import StartView, ItemShopListView

app_name = 'fendi'

urlpatterns = [
    path('', StartView.as_view(), name='index'),
    path('shop_list', ItemShopListView.as_view(), name='shop_list'),
]

fendi_shop/fendi_shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fendi.urls')),
]

fendi_shop/fendi/models.py
from django.db import models

# Create your models here.


class Image(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Size(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name


class Color(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name


class ItemShop(models.Model):

    title = models.CharField(max_length=120)
    description = models.TextField()
    size = models.ManyToManyField(Size)
    image = models.ManyToManyField(Image)
    price = models.CharField(max_length=50)
    color = models.ManyToManyField(Color)
    status = models.BooleanField(default=False)

    def __str__(self):
        return '{} {}'.format(self.title, self.price)

fendi_shop/fendi/views.py
import redis
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView
from .models import ItemShop

# Create your views here.


class StartView(View):
    r = redis.Redis(host='localhost', port=6379)
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        return render(self.request, self.template_name)

    def post(self, request, *args, **kwargs):
        url = self.request.POST.get('url_scrapy')
        self.r.lpush('fendi:start_urls', url)
        context = {'message': 'Please wait scraping process is running'}
        return render(self.request, self.template_name, context)


class ItemShopListView(ListView):

    template_name = 'shop.html'
    queryset = ItemShop.objects.filter(status=True)
    context_object_name = 'item_list'
    paginate_by = 10

fendi_shop/fendi/templates/base.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
  <title>Fendi Shop</title>

</head>
  <link rel="stylesheet" type="text/css" href="{%static 'css/fendi.css'%}">
<body>

  <div class="parent">
    <div class="block">
        {%block content%}
        {%endblock%}
    </div>
  </div>
</body>
</html>

fendi_shop/fendi/templates/index.html
{% extends "base.html" %}
{%block content%}
	{%if not message%}
	<form action="{% url 'fendi:index' %}" method="POST">
		{%csrf_token%}
		<input type="text" name="url_scrapy" size="100">
   		<button type="submit">Run Spider</button>
	</form>
	{%endif%}
	{%if message%}
		<p>{{message}}</p>
		<a href="{%url 'fendi:shop_list' %}"><button>Item List</button></a>
	{%endif%}
{%endblock%}

fendi_shop/fendi/templates/shop.html
{% extends "base.html" %}


{%block content%}
	{%if item_list%}
		{% if is_paginated %}
        <div class="pagination" align="center">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/shop_list?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/shop_list?page={{ page_obj.next_page_number }}">Next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
    <br><br>
	{%for item  in item_list%}
		<p><img src="{{item.image.first}}" alt="{{item.title}}" height='200' width="200" align="left"></p>
		<h2>{{item.title}}</h2>
		<h3>Description:</h3>
		<p>{{item.description}}</p>
		<p>Price:{{item.price}}  
		   Color: 
	   		{%for c in item.color.all%}
	   			{{c.name}}
	   		{%endfor%}
		</p>
		{%if item.size.all%}
		<p>
			<select>
				<option disabled>Size:</option>
				{%for s in item.size.all%}	    		
	    			<option value="{{s.name}}">{{s.name}}</option>
	    		{%endfor%}
	   	    </select>
	   	</p>
	   	{%endif%}
	   	<p>
	   	</p>
	   	<br>
	   	<hr align="left">
	{%endfor%}
	{% if is_paginated %}
        <div class="pagination" align='center'>
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/shop_list?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/shop_list?page={{ page_obj.next_page_number }}">Next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
    <br>
    <br>
    <br>
	{%else%}
	<p>
		Scraping not finished, please wait a few minutes and reload this page
	</p>
	{%endif%}
{%endblock%}